commands:
  #horas
  - command:

    input: gaia Que horas são?
    entity: time
    action: getTime
  - command:
    input: gaia Me diga as horas.
    entity: time
    action: getTime
  - command:
    input: gaia Pode me dizer que horas são?
    entity: time
    action: getTime
  - command:
    input: gaia horas?
    entity: time
    action: getTime

  #data

  - command:
    input: gaia Qual é a data de hoje?
    entity: time
    action: getDate
  - command:
    input: gaia Data de hoje?
    entity: time
    action: getDate
  - command:
    input: gaia Me fale a data atual.
    entity: time
    action: getDate

  #Tempo

  - command:
    input: gaia Previsão do tempo.
    entity: weather
    action: getWeather
  - command:
    input: gaia Como está o clima.
    entity: weather
    action: getWeather
  - command:
    input: gaia Qual é a previsão do tempo?
    entity: weather
    action: getWeather

  #Open

  - command:
    input: gaia Abrir bloco de notas
    entity: open
    action: notas
  - command:
    input: gaia notas
    entity: open
    action: notas
  - command:
    input: gaia abrir notas
    entity: open
    action: notas

  - command:
    input: gaia abrir brave
    entity: open
    action: brave
  - command:
    input: gaia abrir o brave
    entity: open
    action: brave
  - command:
    input: gaia abrir o bravi
    entity: open
    action: brave

  - command:
    input: gaia abrir sigaa
    entity: open
    action: sigaa
  - command:
    input: gaia abrir siga
    entity: open
    action: sigaa
  - command:
    input: gaia abrir o siga
    entity: open
    action: sigaa

  - command:
    input: gaia abrir instagram
    entity: open
    action: insta
  - command:
    input: gaia abrir insta
    entity: open
    action: insta
  - command:
    input: gaia abrir o instagram
    entity: open
    action: insta

  - command:
    input: gaia abrir youtube
    entity: open
    action: youtube
  - command:
    input: gaia abrir o youtube
    entity: open
    action: youtube
  - command:
    input: gaia youtube
    entity: open
    action: youtube

  #Close

  - command:
    input: gaia fechar bloco de notas
    entity: close
    action: notas
  - command:
    input: gaia feche bloco de notas
    entity: close
    action: notas

  #Conversar
  - command:
    input: gaia oi tudo bem?
    entity: fala
    action: normal
  
  #Informações
  - command:
    input: gaia qual meu sistema operacional?
    entity: inf
    action: so
  - command:
    input: gaia qual meu processador?
    entity: inf
    action: process
  - command:
    input: gaia qual tipo de leitura de bits?
    entity: inf
    action: bit


    