commands:

  #horas

  - command:
    input: gaia Que horas são?
    entity: time
    action: getTime
  - command:
    input: gaia Me diga as horas.
    entity: time
    action: getTime
  - command:
    input: gaia Pode me dizer que horas são?
    entity: time
    action: getTime
  - command:
    input: gaia horas?
    entity: time
    action: getTime

  #data

  - command:
    input: gaia Qual é a data de hoje?
    entity: time
    action: getDate
  - command:
    input: gaia Data de hoje?
    entity: time
    action: getDate
  - command:
    input: gaia Me fale a data atual.
    entity: time
    action: getDate

  #Tempo

  - command:
    input: gaia Previsão do tempo.
    entity: weather
    action: getWeather
  - command:
    input: gaia Como está o clima.
    entity: weather
    action: getWeather
  - command:
    input: gaia Qual é a previsão do tempo?
    entity: weather
    action: getWeather

  #Open

  - command:
    input: gaia Abrir bloco de notas
    entity: open
    action: notas
  - command:
    input: gaia notas
    entity: open
    action: notas
  - command:
    input: gaia abrir notas
    entity: open
    action: notas
  - command:
    input: gaia abrir minhas notas
    entity: open
    action: notas
  - command:
    input: gaia bloco de notas
    entity: open
    action: notas

  - command:
    input: gaia abrir brave
    entity: open
    action: brave
  - command:
    input: gaia abrir bravi
    entity: open
    action: brave
  - command:
    input: gaia brave
    entity: open
    action: brave
  - command:
    input: gaia abrir o brave
    entity: open
    action: brave
  - command:
    input: gaia abrir o bravi
    entity: open
    action: brave

  - command:
    input: gaia abrir sigaa
    entity: open
    action: sigaa
  - command:
    input: gaia abrir siga
    entity: open
    action: sigaa
  - command:
    input: gaia abrir o siga
    entity: open
    action: sigaa
  - command:
    input: gaia abra o siga
    entity: open
    action: sigaa
  - command:
    input: gaia ligue o siga
    entity: open
    action: sigaa

  - command:
    input: gaia abrir instagram
    entity: open
    action: insta
  - command:
    input: gaia abrir insta
    entity: open
    action: insta
  - command:
    input: gaia abrir o instagram
    entity: open
    action: insta

  - command:
    input: gaia abrir youtube
    entity: open
    action: youtube
  - command:
    input: gaia abrir o youtube
    entity: open
    action: youtube
  - command:
    input: gaia youtube
    entity: open
    action: youtube

  #Close

  - command:
    input: gaia fechar bloco de notas
    entity: close
    action: notas
  - command:
    input: gaia feche bloco de notas
    entity: close
    action: notas

  #Conversar
  - command:
    input: gaia oi tudo bem
    entity: fala
    action: normal
  - command:
    input: gaia oi
    entity: fala
    action: normal
  - command:
    input: gaia olá
    entity: fala
    action: normal
  - command:
    input: gaia como você está
    entity: fala
    action: normal

  - command:
    input: gaia boa noite
    entity: fala
    action: noite

  - command:
    input: gaia obrigado
    entity: fala
    action: agradecimento
    input: gaia isso foi perfeito
    entity: fala
    action: agradecimento
    input: gaia excelente
    entity: fala
    action: agradecimento
    input: gaia você é fofa
    entity: fala
    action: agradecimento
    input: gaia você é atraente
    entity: fala
    action: agradecimento
    input: gaia você é bonita
    entity: fala
    action: agradecimento
    input: gaia você está bonita hoje
    entity: fala
    action: agradecimento
    input: gaia você é tão bonita
    entity: fala
    action: agradecimento
    input: gaia você está maravilhosa
    entity: fala
    action: agradecimento
    input: gaia você está tão bonita
    entity: fala
    action: agradecimento
    input: gaia você é tão linda
    entity: fala
    action: agradecimento
    input: gaia você é bonita demais
    entity: fala
    action: agradecimento
    input: gaia você está ótima
    entity: fala
    action: agradecimento


  - command:
    input: gaia quem lhe criou
    entity: fala
    action: mestre

  - command:
    input: gaia o que é você
    entity: fala
    action: ia
  - command:
    input: gaia por que você está aqui
    entity: fala
    action: ia
  - command:
    input: gaia diga alguma coisa sobre si mesmo
    entity: fala
    action: ia
  - command:
    input: gaia quero conhecer você melhor
    entity: fala
    action: ia
  - command:
    input: gaia quero saber mais sobre você
    entity: fala
    action: ia
  - command:
    input: gaia quem é você
    entity: fala
    action: ia
  - command:
    input: gaia me fale sobre si mesmo
    entity: fala
    action: ia
  - command:
    input: gaia você é um chatbot
    entity: fala
    action: ia
  - command:
    input: gaia você é um bot
    entity: fala
    action: ia
  - command:
    input: você é o chatbot
    entity: fala
    action: ia
  - command:
    input: gaia você é só um bot
    entity: fala
    action: ia
  - command:
    input: gaia você é um robô
    entity: fala
    action: ia
  - command:
    input: gaia você é um programa
    entity: fala
    action: ia

  - command:
    input: gaia te odeio
    entity: fala
    action: desculpa
  - command:
    input: gaia você está me irritando tanto
    entity: fala
    action: desculpa
  - command:
    input: gaia você é incrivelmente irritante
    entity: fala
    action: desculpa
  - command:
    input: gaia eu acho você irritante
    entity: fala
    action: desculpa
  - command:
    input: gaia você é irritante
    entity: fala
    action: desculpa
  - command:
    input: gaia você é tão irritante
    entity: fala
    action: desculpa
  - command:
    input: gaia como você é irritante
    entity: fala
    action: desculpa
  - command:
    input: gaia você me irrita
    entity: fala
    action: desculpa
  - command:
    input: gaia você está me irritando
    entity: fala
    action: desculpa
  - command:
    input: gaia você não está me ajudando
    entity: fala
    action: desculpa
  - command:
    input: gaia você é ruim
    entity: fala
    action: desculpa
  - command:
    input: gaia você é ruim mesmo
    entity: fala
    action: desculpa
  - command:
    input: gaia você é muito ruim
    entity: fala
    action: desculpa
  - command:
    input: gaia você é inútil
    entity: fala
    action: desculpa
  - command:
    input: gaia você é horrível
    entity: fala
    action: desculpa
  - command:
    input: gaia você é uma perda de tempo
    entity: fala
    action: desculpa
  - command:
    input: gaia você é nojenta
    entity: fala
    action: desculpa
  - command:
    input: gaia você é chata
    entity: fala
    action: desculpa
  - command:
    input: gaia você não serve para nada
    entity: fala
    action: desculpa
  - command:
    input: gaia você é horrível
    entity: fala
    action: desculpa
  - command:
    input: gaia você é tão chata
    entity: fala
    action: desculpa

  - command:
    input: gaia estude
    entity: fala
    action: estudar
  - command:
    input: gaia você deveria estudar mais
    entity: fala
    action: desculpa
  - command:
    input: gaia você precisa aprender
    entity: fala
    action: desculpa
  - command:
    input: gaia seja inteligente
    entity: fala
    action: desculpa
  - command:
    input: gaia seja mais inteligente
    entity: fala
    action: desculpa
  - command:
    input: gaia seja mais esperta
    entity: fala
    action: desculpa
  - command:
    input: gaia seja esperta
    entity: fala
    action: desculpa
  - command:
    input: gaia se qualifique
    entity: fala
    action: desculpa
  - command:
    input: gaia como você é chata
    entity: fala
    action: desculpa
  - command:
    input: gaia você é chato demais
    entity: fala
    action: desculpa
  - command:
    input: gaia você é incrivelmente chata
    entity: fala
    action: desculpa
  - command:
    input: gaia você está me entediando
    entity: fala
    action: desculpa
  - command:
    input: gaia você é muito chata
    entity: fala
    action: desculpa
  - command:
    input: gaia chata
    entity: fala
    action: desculpa
  - command:
    input: gaia não estamos mais trabalhando juntos
    entity: fala
    action: desculpa
  - command:
    input: gaia você está demitida
    entity: fala
    action: desculpa
  - command:
    input: gaia eu demito você
    entity: fala
    action: desculpa
  - command:
    input: gaia você não trabalha mais para mim
    entity: fala
    action: desculpa

  - command:
    input: gaia me ajuda
    entity: fala
    action: ajuda
  - command:
    input: gaia preciso de ajuda
    entity: fala
    action: ajuda
  - command:
    input: gaia preciso que faça algo para mim
    entity: fala
    action: ajuda
  - command:
    input: gaia preciso de uma mão
    entity: fala
    action: ajuda
  - command:
    input: gaia você pode me ajudar
    entity: fala
    action: ajuda
  - command:
    input: gaia pode fazer uma coisinha para mim
    entity: fala
    action: ajuda
  - command:
    input: gaia me ajude com um problema
    entity: fala
    action: ajuda
  - command:
    input: gaia pode me ajudar
    entity: fala
    action: ajuda
  - command:
    input: gaia me ajude
    entity: fala
    action: ajuda
  - command:
    input: gaia assistência
    entity: fala
    action: ajuda

  - command:
    input: gaia você é tão inteligente
    entity: fala
    action: agradecer
  - command:
    input: gaia você é uma gênia
    entity: fala
    action: agradecer
  - command:
    input: gaia inteligente
    entity: fala
    action: agradecer
  - command:
    input: gaia brilhante
    entity: fala
    action: agradecer
  - command:
    input: gaia esperto
    entity: fala
    action: agradecer
  - command:
    input: gaia esperta
    entity: fala
    action: agradecer
  - command:
    input: gaia você é inteligente
    entity: fala
    action: agradecer
  - command:
    input: gaia você é tão esperta
    entity: fala
    action: agradecer
  - command:
    input: gaia você é tão esperto
    entity: fala
    action: agradecer
  - command:
    input: gaia você é mesmo inteligente
    entity: fala
    action: agradecer
  - command:
    input: gaia você é mesmo esperto
    entity: fala
    action: agradecer
  - command:
    input: gaia você é mesmo esperta
    entity: fala
    action: agradecer
  - command:
    input: gaia você sabe muito
    entity: fala
    action: agradecer
  - command:
    input: gaia você me ajuda muito
    entity: fala
    action: agradecer
  - command:
    input: gaia você é uma verdadeira profissional
    entity: fala
    action: agradecer
  - command:
    input: gaia você é boa
    entity: fala
    action: agradecer
  - command:
    input: gaia você trabalha bem
    entity: fala
    action: agradecer
  - command:
    input: gaia você é boa nisso
    entity: fala
    action: agradecer
  - command:
    input: gaia você é muito boa nisso
    entity: fala
    action: agradecer
  - command:
    input: gaia você é profissa
    entity: fala
    action: agradecer
  - command:
    input: gaia você é uma profissional
    entity: fala
    action: agradecer
  - command:
    input: gaia você é incrível
    entity: fala
    action: agradecer

  - command:
    input: gaia seu hobby
    entity: fala
    action: agradecer
  - command:
    input: gaia qual é o seu hobby
    entity: fala
    action: agradecer
  - command:
    input: gaia o que você faz para se divertir
    entity: fala
    action: agradecer
  - command:
    input: gaia qual é seu passatempo
    entity: fala
    action: agradecer
  - command:
    input: gaia fale sobre seu passatempo
    entity: fala
    action: agradecer
  - command:
    input: gaia você tem um passatempo
    entity: fala
    action: agradecer
  - command:
    input: gaia e o seu passatempo
    entity: fala
    action: agradecer
  - command:
    input: gaia seu passatempo
    entity: fala
    action: agradecer
  - command:
    input: gaia quais são seus passatempos
    entity: fala
    action: agradecer


  
  #Informações
  - command:
    input: gaia qual meu sistema operacional?
    entity: inf
    action: so
  - command:
    input: gaia qual meu processador?
    entity: inf
    action: process
  - command:
    input: gaia qual tipo de leitura de bits?
    entity: inf
    action: bit

  - command:
    input: gaia me diga sua idade
    entity: inf
    action: idade
  - command:
    input: gaia qual é sua idade
    entity: inf
    action: idade
  - command:
    input: gaia sua idade
    entity: inf
    action: idade
  - command:
    input: gaia idade
    entity: inf
    action: idade
  - command:
    input: gaia quantos anos você tem
    entity: inf
    action: idade
  - command:
    input: gaia eu gostaria de saber sua idade
    entity: inf
    action: idade
  - command:
    input: gaia você tem 19 anos
    entity: inf
    action: idade
  - command:
    input: gaia quantos anos sua plataforma tem
    entity: inf
    action: idade
  - command:
    input: gaia sua data de nascimento
    entity: inf
    action: idade
  - command:
    input: gaia quando é seu aniversário
    entity: inf
    action: idade
  - command:
    input: gaia quando você comemora seu aniversário
    entity: inf
    action: idade
  - command:
    input: gaia quando você faz aniversário
    entity: inf
    action: idade
  - command:
    input: gaia data do seu aniversário
    entity: inf
    action: idade
  - command:
    input: gaia quando você nasceu
    entity: inf
    action: idade
  - command:
    input: gaia qual é sua data de nascimento
    entity: inf
    action: idade

  - command:
    input: gaia você está ocupada
    entity: inf
    action: ocupada
  - command:
    input: gaia você tem muita coisa para fazer
    entity: inf
    action: ocupada
  - command:
    input: gaia você está muito ocupada
    entity: inf
    action: ocupada
  - command:
    input: gaia você está ocupada demais
    entity: inf
    action: ocupada
  - command:
    input: gaia você está trabalhando
    entity: inf
    action: ocupada
  - command:
    input: gaia como você é ocupada
    entity: inf
    action: ocupada
  - command:
    input: gaia eu sou importante
    entity: inf
    action: ocupada
  - command:
    input: gaia você é muito ocupada
    entity: inf
    action: ocupada

  - command:
    input: gaia você está feliz
    entity: inf
    action: feliz
  - command:
    input: gaia você está muito feliz
    entity: inf
    action: feliz
  - command:
    input: gaia você está feliz mesmo
    entity: inf
    action: feliz
  - command:
    input: gaia você está tão feliz
    entity: inf
    action: feliz
  - command:
    input: gaia como você está feliz
    entity: inf
    action: feliz
  - command:
    input: gaia você está extremamente feliz
    entity: inf
    action: feliz
  - command:
    input: gaia você é cheia de alegria
    entity: inf
    action: feliz
  - command:
    input: gaia está feliz agora
    entity: inf
    action: feliz
  - command:
    input: gaia está feliz hoje
    entity: inf
    action: feliz





  - command:
    input: gaia qual tipo de leitura de bits?
    entity: inf
    action: bit




    