commands:
  #horas
  - command:
    input: gaia Que horas são?
    entity: time
    action: getTime
  - command:
    input: gaia Me diga as horas.
    entity: time
    action: getTime
  - command:
    input: gaia Pode me dizer que horas são?
    entity: time
    action: getTime
  - command:
    input: gaia horas?
    entity: time
    action: getTime
  #data
  - command:
    input: gaia Qual é a data de hoje?
    entity: time
    action: getDate
  - command:
    input: gaia Data de hoje?
    entity: time
    action: getDate
  - command:
    input: gaia Me fale a data atual.
    entity: time
    action: getDate
  #Tempo
  - command:
    input: gaia Previsão do tempo.
    entity: weather
    action: getWeather
  - command:
    input: gaia Como está o clima.
    entity: weather
    action: getWeather
  - command:
    input: gaia Qual é a previsão do tempo?
    entity: weather
    action: getWeather
  #Open
  - command:
    input: gaia Abrir bloco de notas
    entity: open
    action: notas
  - command:
    input: gaia abrir brave
    entity: open
    action: brave
  - command:
    input: gaia abrir sigaa
    entity: open
    action: sigaa
  - command:
    input: gaia abrir instagram
    entity: open
    action: insta
  #Close
  - command:
    input: gaia fechar bloco de notas
    entity: close
    action: notas
  - command:
    input: gaia feche bloco de notas
    entity: close
    action: notas
  #Desligar
  - command:
    input: gaia Desligar
    entity: close
    action: close
  #Conversar
  - command:
    input: gaia oi tudo bem?
    entity: fala
    action: normal

    